---

- name: Install Geo utilities
  dnf: 
    # add: 'tilemill', 'gdal-bin', 'libspatialite-dev', 'spatialite-bin'
    name: ['sqlite','python-matplotlib','python-gdal','spatialite-gui','sqliteman']
    state: present
    update_cache: True

- name: Install global python packages
  pip:
    name: ['geopandas', 'shapely', 'pyshp', 'geopy', 'pyproj', 'scikit-learn']
    executable: pip3
    state: present